package p1;
// Generated Dec 22, 2019 8:10:44 PM by Hibernate Tools 3.2.1.GA



/**
 * Employee generated by ghanshyam
 */
public class Employee  implements java.io.Serializable {


     private int eid;
     private String firstno;
     private String lastno;
     private String email;

    public Employee() {
    }

	
    public Employee(int eid) {
        this.eid = eid;
    }
    public Employee(int eid, String firstno, String lastno, String email) {
       this.eid = eid;
       this.firstno = firstno;
       this.lastno = lastno;
       this.email = email;
    }
   
    public int getEid() {
        return this.eid;
    }
    
    public void setEid(int eid) {
        this.eid = eid;
    }
    public String getFirstno() {
        return this.firstno;
    }
    
    public void setFirstno(String firstno) {
        this.firstno = firstno;
    }
    public String getLastno() {
        return this.lastno;
    }
    
    public void setLastno(String lastno) {
        this.lastno = lastno;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


